#!/usr/bin/env bash
# add subdomians and show them using the dig command $1 domain $2 subdomain

domain=$1

if [ "$#" = 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")

    for sub_domain in "${subdomains[@]}"; do
        record_type=$(dig "$sub_domain"."$domain" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
        destination=$(dig "$sub_domain"."$domain" | grep -A1 'ANSWER SECTION' | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b')
        echo "The subdomain $sub_domain is a $record_type record and points to $destination"
    done

elif [ $# = 2 ]; then
    record_type=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    destination=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b')
    echo "The subdomain $2 is a $record_type record and points to $destination"
fi
