#!/usr/bin/env bash
# install nginx server

sudo apt-get update -y
sudo apt-get install nginx -y

sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
