#!/usr/bin/env bash
# install nginx server
# ./0-transfer_file 1-install_nginx_web_server 18.210.14.47 ubuntu ~/.ssh/id_rsa

sudo apt-get update -y
sudo apt-get install nginx -y

sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
