#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

# install nginx server
sudo apt-get update -y
sudo apt-get install nginx -y

sudo mkdir -p /var/www/html
#  sets the content of the index.html file to "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a custom HTML file with "301 Moved Permanently" content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/not_found.html

# Modify Nginx configuration to implement the redirect
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me /not_found permanent;" /etc/nginx/sites-available/default

# Configure Nginx server to redirect to the custom 404 page
sudo sed -i "/listen 80 default_server/a error_page 404 /not_found;" /etc/nginx/sites-available/default

sudo service nginx restart
