#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

# check for updates and install the HAproxy
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 433531-web-01 18.210.14.47:80 check
    server 433531-web-02 54.157.179.130:80 check
" >>/etc/haproxy/haproxy.cfg

# Start the HAProxy
sudo service haproxy restart
