#!/usr/bin/env bash
# install nginx server
sudo apt-get update -y
sudo apt-get install nginx -y
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
