#!/usr/bin/env bash
# make the nginx sercer listen to port 80 put using shorter version
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx
