#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

newfile="/var/run/myscript.pid"

echo "$$" > "$newfile"


while true ; do 

    termination_handler ()
        {
        echo "I hate the kill command"
        exit 0
        } 
    trap termination_handler SIGTERM
    
    
    sigint_handler() 
        {
        echo "Y U no love me?!"
        rm "$newfile"
        exit 0
        }
    trap sigint_handler SIGINT
    
    sigquit_handler()
        {
        rm "$newfile"
        exit 0
        }
    trap sigquit_handler SIGQUIT
    
    
    echo "To infinity and beyond"
    sleep 2
    
done
