#!/usr/bin/env bash
# displays Best School 10 times
#+for the 9th iteration, displays Best School and then Hi on a new line.

for ((i = 0; i < 10; i++))
do
echo "Best School"

if ((i == 8))
then
echo "Hi"
fi

done
