#!/usr/bin/env bash
# displays Best School 10 times
#+for the 9th iteration, displays Best School and then Hi on a new line.
i=1
while ((i <= 10))
do

if ((i == 4))
then
echo "bad luck"

elif ((i == 8))
then
echo "good luck"

else
echo "Best School"
fi

((i++))
done
