#!/usr/bin/env bash
# change the nginx user to be nginx

# copy the confg file
cp /etc/nginx/nginx.conf /etc/nginx/nginx_confg.cpy

# Insert the 'user nginx' line at the beginning of the nginx.conf file
sed -i '1i\user nginx;' /etc/nginx/nginx.conf

# nginx must be listening on all active IPs on port 8080
# sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i -E "s/(listen.*)80 /\18080 /g" /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo service nginx restart
